### ISSUE TITLE
Open a course by opening an enrollment URL

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#11]
**Describe the feature you'd like**

Allow users to join a course by opening an enrollment URL

**Comment by ujjwalagrawal17** [comment]
@ragesoss I am a little bit confused about this feature. Will the user get the enrollment URL in email? If yes, then I think this feature is needed in the app.

**Comment by ragesoss** [comment]
Yes, either by email or possibly a link posted on a wiki page or the like. It will be of this form: https://outreachdashboard.wmflabs.org/courses/MoMA/MoMA_ArtAndFeminism_2019?enroll=abcde

**Comment by ujjwalagrawal17** [comment]
So the link now open app instead of website if the app is installed on the phone? I am not sure but I think we may need to make some changes in the website page also so that it redirects the user to open app. Or I will check for other solutions for opening app via a link. 

![wikiedudb](https://user-images.githubusercontent.com/19607555/53446698-92af0000-3a39-11e9-8bbb-5567912853aa.png)
.

**Comment by ragesoss** [comment]
Cool. If you do find that website changes are necessary, let's discuss it in chat.
