### ISSUE TITLE
Make use of custom adapter for recycler view's

### ISSUE THREAD

**Issue by victorvicari** [WikiEducationFoundation/apps-android-wikiedudashboard#111]
There are a lot of boilerplate in every recycler view. Try to reduce all of it, or at least a good lines of code to increase readbility.

**Comment by lovisgod** [comment]
Hi, @victorvicari  I want to contribute to this project and will love to take up this issue.

**Comment by victorvicari** [comment]
Hi, @lovisgod. I appreciate the interest... but actually I'm just few adjust away of delivering it. Although, you can talk to @ujjwalagrawal17 . See what are his thought's about any of the possible new issues.
