### ISSUE TITLE
[BUG] UI issue in activity_course_detail.xml

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#113]
**Summary:** 

After merging #86 ,there is a minor UI issue in activity_course_detail, we are unable to see the top layout of fragment, it is getting hidden below the toolbar, tablayout. 

**Steps to reproduce:** 

- Open Course Details Page. (You can see articles created, articles edited are not visible in the screen)
 
**Screen-shots:** 

![image](https://user-images.githubusercontent.com/19607555/66435956-93822880-ea43-11e9-8588-d1eb2e9dadf8.png)

**Would you like to work on the issue?**

No

**Comment by MarinaTaran** [comment]
Can I take it?

**Comment by ujjwalagrawal17** [comment]
Yup. You can work on it.

**Comment by MarinaTaran** [comment]
Sorry,you mean you don't see this one?
![!!!!!!!!!!!!!!!](https://user-images.githubusercontent.com/42735198/66565064-33d26d00-eb6a-11e9-903f-9e42575a04e2.jpg)

**Comment by ujjwalagrawal17** [comment]
Yes. You need to pull the code from master to reproduce this issue. This was working fine earlier and is not visible in my device as of now.

**Comment by MarinaTaran** [comment]
when this part of code  <androidx.viewpager.widget.ViewPager
            android:id="@+id/viewPager"
            android:layout_width="match_parent"
            android:layout_height="match_parent" /> 
out of linearlayout it doesn't show articles edited. But maybe someone fixd it because I have all correct.
![!!!!!!!!!!!!!!!](https://user-images.githubusercontent.com/42735198/66568837-e3abd880-eb72-11e9-8204-d0a29cd4aaef.jpg)

**Comment by MarinaTaran** [comment]
I took new last code, like I opened new project

**Comment by MarinaTaran** [comment]
Ok. Now I see!!!

**Comment by kulloveth** [comment]
@MarinaTaran  @ujjwalagrawal17 I just pulled its still like that so i fixed it with setting layout_height to wrapContent and changing app:layout_constraintTop_toTopof="parent" to app:layout_constraintTop_toBottomOf="@id/appBarLayout4" so @MarinaTaran you can just do that and create a PR

**Comment by kulloveth** [comment]
> did you change it in AppBarLayout? @kulloveth

no, viewpager is where you do that @MarinaTaran

**Comment by MarinaTaran** [comment]
I got it. I just ask you because I tried already everithing but it doesn't work.Now I restarted my android stodio and it works. Thanks.I actually added just linearlayout and it works but off cours your idea beter.@kulloveth

**Comment by kulloveth** [comment]
> I got it. I just ask you because I tried already everithing but it doesn't work.Now I restarted my android stodio and it works. Thanks.I actually added just linearlayout and it works but off cours your idea beter.@kulloveth

@MarinaTaran welldone but then converting all traditional layouts to constraintLayout is one of  the issues we are trying to solve. check  #62 so it has to be in constraint

**Comment by MarinaTaran** [comment]
we converted relativeLayout to constraintlayout ,but inside constraintlayout i thought we can have linerlayout?!I didn't put just instead constraintlayout linerlayout,i put inside,maybe it isn't good idea:)@kulloveth

**Comment by kulloveth** [comment]
> we converted relativeLayout to constraintlayout ,but inside constraintlayout i thought we can have linerlayout?!I didn't put just instead constraintlayout linerlayout,i put inside,maybe it isn't good idea:)@kulloveth

thats in very rare situations where cardView is involved with so many child views positoned beside each other and constraint is used instead but then we are trying to avoid all nested Layouts every where possible and in this case it can be avoided. I suggest you just revert to the original code and then change the viewPager section just the way I proposed. It will solve it  perfectly

**Comment by MarinaTaran** [comment]
I agree with you! Just asked you opinion :). Thanks!

**Comment by ujjwalagrawal17** [comment]
I was able to reproduce the same issue in my dashboard fragment today.

**Comment by kulloveth** [comment]
@ujjwalagrawal17  can i help

**Comment by ujjwalagrawal17** [comment]
Resolved in #150

**Comment by ujjwalagrawal17** [comment]
@MarinaTaran please pick up other issues.
