### ISSUE TITLE
[sub issue] Use ConstraintLayout in fragment_explore_course_list.xml

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#142]
**Change to Constraint Layout**
- Change the fragment_explore_course_list layout to Constraint layout

**Would you like to work on the issue?**
Yes

**Comment by MarinaTaran** [comment]
will I work on this?

**Comment by gconnect** [comment]
You cab work on it.

**Comment by ujjwalagrawal17** [comment]
Resolved in #187
