### ISSUE TITLE
[sub issue] Use ConstraintLayout in fragment_explore_students.xml

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#143]
**Change to Constraint Layout**
- Change the fragment_explore_students layout to Constraint layout

**Would you like to work on the issue?**
Yes

**Comment by mayokunthefirst** [comment]
Hello @gconnect , I'll love to get on this

**Comment by gconnect** [comment]
@mayokunthefirst you can start working on it. This task is now assigned to you.

**Comment by gconnect** [comment]
@mayokunthefirst are you still working on it?

**Comment by mayokunthefirst** [comment]
@gconnect Yes I am, should send in the Pull Request today.
