### ISSUE TITLE
Fix Leaks in App (can be analyzed using leakcanary. )

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#144]
**Summary:** 

Using app in debug mode. You can find many leaks throughout the app. We need to fix them. I will add some of them in the comments. Others can also add the leaks here in this issue/open a new issue. 

**Steps to reproduce:** 

Play around with the app. 

**Would you like to work on the issue?**

No.

**Comment by kulloveth** [comment]
hey @ujjwalagrawal17  so from the leakCanary I figured most of the leaks are from views still lying around after there fragment are no longer visible. dont  you think using butterKnife to bind these views which will be unbind on DestroyView method will help reduce the leak?

**Comment by ujjwalagrawal17** [comment]
Hi @kulloveth we are planning to remove findviewbyid, butterknife and follow https://kotlinlang.org/docs/tutorials/android-plugin.html#view-binding for viewbinding.

**Comment by kulloveth** [comment]
> Hi @kulloveth we are planning to remove findviewbyid, butterknife and follow https://kotlinlang.org/docs/tutorials/android-plugin.html#view-binding for viewbinding.

ok, looking into it

**Comment by ujjwalagrawal17** [comment]
I am closing the parent issue. We will do the discussions in sub-issues (the actual memory leaks) from now.
