### ISSUE TITLE
[BUG] UI issue in Media Details Page

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#146]
**Summary:** 

The padding in category item, file usage item is not looking good. We need to make them consistent with other layouts. 

**Steps to reproduce:** 

Open Media Details Page
 
**Screen-shots:** 

![image](https://user-images.githubusercontent.com/19607555/67163956-ebe5ee00-f392-11e9-845c-2ed99d1dcc06.png)

**Would you like to work on the issue?**

No.

**Comment by ngumbau** [comment]
I would like to work on this issue if it is okay with the team.  In addition, is it possible to update the README with the slack channel details so I can introduce myself?

**Comment by ujjwalagrawal17** [comment]
Hi @ngumbau sure feel free to start working on it. I will update the readme but the slack channel isn't open for everyone so please share your email ID with me. I will ask Sage to send you an invite.

**Comment by ngumbau** [comment]
kkibwana@gmail.com

**Comment by Darshpreet2000** [comment]
I want to work on this issue, my email id is dsingh200021@gmail.com.
Invite me also.
