### ISSUE TITLE
[Sub issue] Use ConstraintLayout in fragment_training.xml

### ISSUE THREAD

**Issue by Anniekobia** [WikiEducationFoundation/apps-android-wikiedudashboard#149]
**Change to Constraint Layout**

    Change the fragment_explore_students layout to Constraint layout

**Would you like to work on the issue?**
Yes

**Comment by gconnect** [comment]
@Anniekobia are you still working on this?

**Comment by gconnect** [comment]
> **Change to Constraint Layout**
> 
> ```
> Change the fragment_training layout to Constraint layout
> ```
> 
> **Would you like to work on the issue?**
> Yes

**Comment by Anniekobia** [comment]
@gconnect yes. I am handling it

**Comment by gconnect** [comment]
Okay. Well-done

**Comment by gconnect** [comment]
@Anniekobia are you still working on this?

**Comment by Anniekobia** [comment]
@gconnect Already did. I am waiting for feedback on the PR

**Comment by amit6663** [comment]
@Anniekobia I want to work on this.

**Comment by amit6663** [comment]
can i work on this issue? @ujjwalagrawal17

**Comment by ujjwalagrawal17** [comment]
Sure @amit6663 , I am assigning this issue to you.

**Comment by ghost** [comment]
@ujjwalagrawal17 Can I work on this issue?

**Comment by ujjwalagrawal17** [comment]
Sure @ankitadhiman003 feel free to take it up.
