### ISSUE TITLE
Format the Start and End Date to Human Readable Dates on the Active Course Detailed Page

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#158]
**Format the Start and End Date to Human Readable Dates**
- The current start and end date  of the Active Course Detailed Page is not human-readable

**Comment by kulloveth** [comment]
@gconnect  am working on this, hope its ok by you?

**Comment by gconnect** [comment]
It's okay. You can go-ahead.
