### ISSUE TITLE
UI issues- Overlapping views on the Explore fragment from the Dashboard Fragment

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#159]
**UI issues- Overlapping views**
- The Dashboard navigation view item overlaps on the explore fragment

![image](https://user-images.githubusercontent.com/23031920/67250286-b14b8680-f462-11e9-9f63-780ab46c37c9.png)
- The fab button also overlapping on the explore fragment
![image](https://user-images.githubusercontent.com/23031920/67250192-60d42900-f462-11e9-837a-f215feada16d.png)

**Comment by MarinaTaran** [comment]
I don't see at all now Active Campaigns and Active courses

**Comment by MarinaTaran** [comment]
yesterday i changed this explore fragment from linearlayout to constraintlayout, so ,now I added some changes to ViewPager can you take a look on them?I will push it

**Comment by gconnect** [comment]
The changes you made on the explore fragment are okay except for a minor constraint issue which I noticed yesterday and I have raised an issue for it because your PR has already been merged to master. 

And I think after you changed the layout to Constraintlayout the over-lapping issue has been fixed. So whats left is to fix the minor constraint issue which I will fix in #173

**Comment by MarinaTaran** [comment]
and about " fab button also overlapping on the explore fragment" isn't it in fragment campaign list? I just raised FloatingActionMenu in  fragment campaign list.

**Comment by gconnect** [comment]
> and about " fab button also overlapping on the explore fragment" isn't it in fragment campaign list? I just raised FloatingActionMenu in fragment campaign list.

Have you fixed the floating action button appearing in explore fragment. If yes you can send a PR and reference this issue

**Comment by ujjwalagrawal17** [comment]
Anyone who wishes to work on it please comment, send a PR.

**Comment by gconnect** [comment]
I have worked on it. @ujjwalagrawal17 please review here #226

**Comment by amit6663** [comment]
> Anyone who wishes to work on it please comment, send a PR.

yeah sir i want to work on this

**Comment by ujjwalagrawal17** [comment]
This is fixed in #226
