### ISSUE TITLE
[sub-issue] Change include_files_media to ConstraintLayout

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#169]
**Change include_files_media to ConstraintLayout**
- Change the LinearLayout to ConstraintLayout

**Would you like to work on the issue?**
Yes

**Comment by MarinaTaran** [comment]
I would like to do it

**Comment by gconnect** [comment]
I am working on it

**Comment by gconnect** [comment]
@ujjwalagrawal17 I have fixed the issue you can review the PR #190
