### ISSUE TITLE
Write unit tests for initial modules - splash screen, login, course list, course details

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#17]
**Describe the feature you'd like**

Write unit tests for initial modules - splash screen, login, course list, course details

**Comment by ujjwalagrawal17** [comment]
The current Code Coverage of the app is 0 %. We will like to increase it to at least 75%.

**Comment by Darshpreet2000** [comment]
I am working on this issue
