### ISSUE TITLE
[sub-issue] Change item_rv_student layout to ConstraintLayout

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#200]
**Change to Constraint Layout**
- Change item_rv_student layout to Constraint layout

**Would you like to work on the issue?**
Yes

**Comment by gconnect** [comment]
@ujjwalagrawal17 am done you can checkout the PR #199

**Comment by kulloveth** [comment]
#155

**Comment by ujjwalagrawal17** [comment]
Closing this as this is same as #155
