### ISSUE TITLE
[sub-issue] Change fragment_recent_activity to ConstraintLayout

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#202]
**Summary:**
- The currrent layout is RelativeLayout

**Steps to reproduce:**
- Change the layout to ConstraintLayout

Would you like to work on the issue?
Yes.

**Comment by gconnect** [comment]
I am on it

**Comment by kulloveth** [comment]
@always check well to make sure issues have not been created #154

**Comment by ujjwalagrawal17** [comment]
Repeat of #154
