### ISSUE TITLE
[sub-issue] Change fragment_profile_stats to ConstraintLayout

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#203]
**Summary:**
The current layout is LinearLayout

**Steps to reproduce:**
Change the layout to ConstraintLayout

**Would you like to work on the issue?**
Yes.

**Comment by gconnect** [comment]
@ujjwalagrawal17 please review #225

**Comment by Bhavnaharitsa** [comment]
@gconnect Is this issue still a valid one? If yes, Could you please assign me to this? :)

**Comment by gconnect** [comment]
The issue has been fixed. I will have to close it now
