### ISSUE TITLE
[BUG]Active course  Detail - App crash on-click activity tab list-items

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#206]
**Summary:** 
- The app crashes onclick on the activity tab list items

**Steps to reproduce:** 
- Run the app and allow it to crash check the log for the error message and fix

**Would you like to work on the issue?**
Yes

**Comment by kulloveth** [comment]
hey @gconnect  i just pulled and  its not crashing. its the image you are talking about right?

**Comment by gconnect** [comment]
It was crashing on my device. Tried it the severally the same thing. But it's okay now.
