### ISSUE TITLE
Alphabetize the Active Campaigns list to make it easier to read

### ISSUE THREAD

**Issue by melissasny1** [WikiEducationFoundation/apps-android-wikiedudashboard#219]
**Describe the feature you'd like**
Modify CampaignListFragment.kt to sort the Active Campaigns list in alphabetical order to make it easier to read.

**Screenshots** (page 1 of 8)

![BEFORE CAMPAIGN LIST](https://user-images.githubusercontent.com/3076267/67720115-8b196f80-f9a9-11e9-8c06-b46f2f0102a4.jpg)

**Would you like to work on the issue?**
Yes

**Comment by melissasny1** [comment]
@ujjwalagrawal17 Please let me know what additional details you would like to add to the course card item.  Also, to confirm that we're referencing the same item, is this an example of the course card you're referring to?

![Course detail](https://user-images.githubusercontent.com/3076267/69206083-beb76780-0b19-11ea-833d-51cd9d28d3e7.jpg)

**Comment by ujjwalagrawal17** [comment]
We don't have any plan of changing the order now. Also there is a seperate issue for adding new items in the list (that is also in low priority issue) so closing this issue now. 

Thanks for your creating the issue and your efforts @melissasny1
