### ISSUE TITLE
[sub-issue] Setup Room database for Local Storage

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#227]
**Database setup for local storage**
- The Room persistent Library will be used for local storage
   Room persistence library provides an abstraction layer over SQLite to allow for more robust database access while harnessing the full power of SQLite.

  The library helps you create a cache of your app's data on a device that's running your app. This cache, which serves as your app's single source of truth, allows users to view a consistent copy of key information within your app, regardless of whether users have an internet connection. [source: Google Android documentation]

**Additional context**
- Currently, the app those not have a local database. There is no cached copy of data fetched from the internet.

**Would you like to work on the issue?**
Yes

**Comment by kiranofans** [comment]
May I ask which part of the Room library you are going to implement with the PR for this feature?

**Comment by gconnect** [comment]
All

**Comment by ujjwalagrawal17** [comment]
This is implemented as a part of #298
