### ISSUE TITLE
Make use of kotlin synthetic for binding views

### ISSUE THREAD

**Issue by victorvicari** [WikiEducationFoundation/apps-android-wikiedudashboard#232]
Kotlin has the synthetic view, wich allow to bind the views without android data binding or findViewById. So, to achieve the a higher code quality, make use of this option to clear the binding boilerplate inside the fragments / activities. This will also make any changes in the code base be more smoothly.

**Comment by kiranofans** [comment]
Can I take this feature?
I think it's to implement the Kotlin extension for view binding

**Comment by ujjwalagrawal17** [comment]
Thanks for the PR @victorvicari !
