### ISSUE TITLE
Add Koin for Dependency Injection

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#25]
**Describe the feature you'd like**

At its core, dependency injection is just the principle of `"tell, dont ask"` put into practice; for instance, if a **class A** needs to use an instance of **class B**, it should be handed an instance of the **class B** rather than reaching out to get it.  This has the effect of decoupling code, making it easier to test and reuse.

We should use Dagger 2 as our dependency injection engine.  This issue alone wont be enough to answer all of your questions, so take a look at a couple of great resources:

* "Dependency Injection with Dagger 2" - https://github.com/codepath/android_guides/wiki/Dependency-Injection-with-Dagger-2
* the Dagger user guide - https://google.github.io/dagger/users-guide.html

**Comment by ujjwalagrawal17** [comment]
https://insert-koin.io/ - seems to have more supprt for kotlin and seems much simpler to implement.

**Comment by gemasr** [comment]
Hi! Can I take this one? it looks like a huge thing but I can start adding the framework to the app and using it in one of the modules (for example in profile in which I have been working recently) and then every time we need to modify a thing in any of the other modules we can check if the DI has been already implemented (or we can divide the work needed by module). What do you think?

**Comment by ujjwalagrawal17** [comment]
Yup, we can divide it based on modules. Although it's not a recommenced task for newcomer, if you think you can add it in profile then go ahead

**Comment by gemasr** [comment]
Nice!
I will create a PR related to this issue with the basic setup (including a test with the Koin `checkModules` method, to check for modules integrity) and then I will do another with the profile (and later I can continue with the rest of the modules, or we can divide them so they can be done in parallel)

**Comment by ujjwalagrawal17** [comment]
Closing this as this is added in #136
