### ISSUE TITLE
[BUG] illegal argument on leaving  a fragment

### ISSUE THREAD

**Issue by kulloveth** [WikiEducationFoundation/apps-android-wikiedudashboard#250]
to reproduce open a course detail then leave the page, wait for a while the app will crash

**Comment by amit6663** [comment]
can i work on this issue? @kulloveth , @ujjwalagrawal17

**Comment by kulloveth** [comment]
> can i work on this issue? @kulloveth , @ujjwalagrawal17

@amit6663  I think this has been fixed. @ujjwalagrawal17 Kindly confirm this. I closed my PR because I figured it was fixed

**Comment by ujjwalagrawal17** [comment]
Yes, this issue is fixed. Thanks, @kulloveth .
