### ISSUE TITLE
Add Android 10 support (Change target SDK to 29)

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#253]
**Describe the feature you'd like**

Add support for Android 10 (Change target SDK to 29).

**Comment by aklapper** [comment]
@ujjwalagrawal17: Which knowledge would someone need to work on this? (And which tags (programming languages, etc) to add on the GCI site?) TIA :)

**Comment by ShridharGoel** [comment]
@aklapper I have added the `android` tag on the GCI site.

**Comment by aklapper** [comment]
@ujjwalagrawal17 , @ShridharGoel : It is still unclear to me as a complete newcomer how much work this is. Replacing one single number in one configuration file and that's all? Porting some deprecated or removed code to newer code after compiling something somehow? Please elaborate a bit in the task on the GCI site by imagining that you're a complete newcomer (or explicitly say how much knowledge is needed in which area if this task is not for complete newcomers). Thanks a lot!
