### ISSUE TITLE
Add placeholder for empty screens

### ISSUE THREAD

**Issue by ShridharGoel** [WikiEducationFoundation/apps-android-wikiedudashboard#254]
**Describe the feature you'd like**

Whenever a page does not have any content to display, for example, an empty RecyclerView, then instead of a blank screen, a 'Nothing to display' or similar message/image should be displayed to the user.

**Would you like to work on the issue?**

No.

**Comment by urbanecm** [comment]
Backlink to GCI interface: https://codein.withgoogle.com/dashboard/tasks/5166702904475648/, published, with number of days available raised to 5.

**Comment by ShcherbaDev** [comment]
Hello! Please check my pull request #257

**Comment by ShridharGoel** [comment]
Fixed in #257
