### ISSUE TITLE
Add better screenshots for Play Store

### ISSUE THREAD

**Issue by ShridharGoel** [WikiEducationFoundation/apps-android-wikiedudashboard#256]
Better screenshots are needed for Play Store, like images in which a mobile device is displaying the screens of the app with proper background and text on the top or bottom.

Inspiration can be taken from here: https://play.google.com/store/apps/details?id=com.whatsapp

**Comment by Siyam009** [comment]
This is a silly question but which apps screenshot should I take and should I post the image here?

**Comment by ShridharGoel** [comment]
Screenshots of this app itself, the Wiki Education Dashboard Android App.

Yes, do post the images here.

**Comment by Siyam009** [comment]
![PicsArt_12-03-08 48 08](https://user-images.githubusercontent.com/38827775/70061822-2b009380-160f-11ea-8c63-31266da8f225.jpg)
![PicsArt_12-03-08 01 42](https://user-images.githubusercontent.com/38827775/70061851-3653bf00-160f-11ea-9ef9-685494e2d384.jpg)
![PicsArt_12-03-08 42 35](https://user-images.githubusercontent.com/38827775/70061872-3f449080-160f-11ea-86da-9ac326a5b3be.jpg)
![PicsArt_12-03-08 48 08](https://user-images.githubusercontent.com/38827775/70061914-4d92ac80-160f-11ea-9df6-cbe48f615bc4.jpg)

**Comment by Siyam009** [comment]
Need more?

**Comment by ujjwalagrawal17** [comment]
You have attached screenshot of the website inside the phone. We need app screenshots of Wiki Education Android app. 

You can check the screenshots in screenshots folder in our GitHub repo or take new screenshots from the live app in Google play store. 

https://play.google.com/store/apps/details?id=org.wikiedufoundation.wikiedudashboard.release

**Comment by Siyam009** [comment]
This is what i get when sign into the app with Wikipedia

Siyam

**Comment by Siyam009** [comment]
Siyam

**Comment by ujjwalagrawal17** [comment]
Ohh, that was a bug in the live app in Google play in some phones. Can you take the screenshots from our repo for now/clone the repo and build the app in your phone using Android studio? 

The bug is fixed now. I will try to deploy another version fixing that bug soon.

**Comment by ujjwalagrawal17** [comment]
If you are a GCI participant. Please claim the task from the GCI website and continue working on it.

**Comment by Siyam009** [comment]
But how can I participate ìf I cant use the app?

Siyam

**Comment by ShridharGoel** [comment]
Why can't you use the app? If you are having some issue using the live app from Play Store, then just build it through Android Studio.

**Comment by Siyam009** [comment]
I don't use Android Studio.I don't know how to build an app

Siyam

**Comment by ShridharGoel** [comment]
Just use the screenshots from here: https://github.com/WikiEducationFoundation/apps-android-wikiedudashboard/tree/master/screenshots

**Comment by Siyam009** [comment]
![PicsArt_12-04-07 48 57](https://user-images.githubusercontent.com/38827775/70147921-69f61e00-16cf-11ea-810c-49176520d212.jpg)
![PicsArt_12-04-07 43 39](https://user-images.githubusercontent.com/38827775/70147934-6febff00-16cf-11ea-8556-ca10d815a835.jpg)
![PicsArt_12-04-07 37 01](https://user-images.githubusercontent.com/38827775/70147945-75494980-16cf-11ea-8c41-320df027f946.jpg)
![Uploading PicsArt_12-04-05.35.37.jpg…]()

**Comment by Siyam009** [comment]
![PicsArt_12-04-05 35 37](https://user-images.githubusercontent.com/38827775/70148094-b9d4e500-16cf-11ea-88bd-82a057173d64.jpg)

**Comment by ShridharGoel** [comment]
@Siyam009 Good work! Please do this for the other screenshots as well which are live on the Play Store: https://play.google.com/store/apps/details?id=org.wikiedufoundation.wikiedudashboard.release

**Comment by Siyam009** [comment]
How can I download screenshots from play store?

Siyam

**Comment by ShridharGoel** [comment]
Get them from here: https://github.com/ujjwalagrawal17/apps-android-wikiedudashboard/tree/master/screenshots

After it's done, send PR to update the screenshots in the `screenshots` folder of the repo.

**Comment by Siyam009** [comment]
![PicsArt_12-05-11 25 31](https://user-images.githubusercontent.com/38827775/70206540-1678e400-1752-11ea-8aab-a738e3b13827.jpg)
![PicsArt_12-05-11 22 55](https://user-images.githubusercontent.com/38827775/70206547-1d075b80-1752-11ea-8122-d241473c1dbb.jpg)
![PicsArt_12-05-11 18 52](https://user-images.githubusercontent.com/38827775/70206556-22fd3c80-1752-11ea-9d2e-4e7c800a0629.jpg)

**Comment by ShridharGoel** [comment]
Screenshot of My Dashboard is still left.

**Comment by Siyam009** [comment]
![PicsArt_12-05-12 20 38](https://user-images.githubusercontent.com/38827775/70209157-b2f2b480-1759-11ea-9bfe-804dad7826c1.jpg)
