### ISSUE TITLE
Add search feature in the Explore tab

### ISSUE THREAD

**Issue by hemilpanchiwala** [WikiEducationFoundation/apps-android-wikiedudashboard#280]
**Describe the feature you'd like**

In the Explore tab of the main screen, a search feature is needed for finding active campaigns as well as active courses. This feature is required to find any needed active campaign/course easily among a long list of active campaigns/courses.

**Screenshots**

Add this feature to both of these pages.
<table>
<tr>
<td>
<img src="https://i.ibb.co/rFnFKJd/Whats-App-Image-2020-01-05-at-17-25-55.jpg" height=300/>
</td>
<td>
<img src="https://i.ibb.co/FmJKsvT/Whats-App-Image-2020-01-05-at-17-25-55-1.jpg" height=300/>
</td>
</tr>
</table>

**Would you like to work on the issue?**

Yes

**Comment by ujjwalagrawal17** [comment]
Hi @hemilpanchiwala , thanks for creating the issue. This feature was available previously but is removed in one of the PR by mistake. Will be nice to add it again. Feel free to start working on it.

**Comment by hemilpanchiwala** [comment]
@ujjwalagrawal17 I have made the PR #282 for this issue.

**Comment by ujjwalagrawal17** [comment]
Re-opening this as it is not working properly now.

**Comment by yash1ts** [comment]
I can work on this.

**Comment by ujjwalagrawal17** [comment]
Sure @yash1ts feel free to work on it. Raise a PR when it's done.
