### ISSUE TITLE
Add Lint Check in CI to improve code formatting. 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#288]
**Describe the feature you'd like**

Add Lint Check to improve code formatting. 

**Would you like to work on the issue?**
No

**Comment by hemilpanchiwala** [comment]
@ujjwalagrawal17 I would like to work on this.

**Comment by ujjwalagrawal17** [comment]
Sure. Feel free to start working on it. After setting up the rules, we need to format the whole codebase too as the CI build will start failing.

**Comment by ujjwalagrawal17** [comment]
https://github.com/pinterest/ktlint looks good to me.  @victorvicari do you have any other suggestions?

**Comment by victorvicari** [comment]
Sure @ujjwalagrawal17 , this one is pretty good

**Comment by hemilpanchiwala** [comment]
@ujjwalagrawal17 I have made PR #305 for this issue
