### ISSUE TITLE
Refactor All DI modules inside a Modules.kt file.  

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#290]
**Describe the feature you'd like**

Refactor the code of the below 4 files inside a Modules.kt file. 

<img width="984" alt="Screenshot 2020-01-07 at 5 22 26 PM" src="https://user-images.githubusercontent.com/19607555/71893775-8c69d400-3172-11ea-8ab9-8b685b66fcd4.png">
 
**Would you like to work on the issue?**
No

**Comment by Darshpreet2000** [comment]
I want to work on this issue
