### ISSUE TITLE
Convert PresenterCallback.java to kotlin

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#291]
**Describe the feature you'd like**

Convert PresenterCallback.java to kotlin

**Would you like to work on the issue?**
No

**Comment by Darshpreet2000** [comment]
Can I work on this issue?

**Comment by ujjwalagrawal17** [comment]
I guess @mistervaibhav is already working on it.

**Comment by ujjwalagrawal17** [comment]
@mistervaibhav if you are not working on this issue let us know. Thanks

**Comment by mistervaibhav** [comment]
> 
> 
> @mistervaibhav if you are not working on this issue let us know. Thanks
@ujjwalagrawal17 , I am working on this issue however i faced certain problems so I closed the PR. I would be opening up a PR soon. Thanks.

**Comment by ujjwalagrawal17** [comment]
Fixed in #307
