### ISSUE TITLE
Show a list of your own courses

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#3]
**Describe the feature you'd like**

Allow users to see a list of your own courses

**Comment by JayjeetAtGithub** [comment]
@ragesoss @ujjwalagrawal17  I would like to solve this issue ? Can you give me some insight on how to start ?

**Comment by ujjwalagrawal17** [comment]
This issue is already made in initial modules. So closing it. @JayjeetAtGithub If you want you can work on other open issues. I just closed some issues that are already made.
