### ISSUE TITLE
UI BUG in Course Details Page

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#304]
**Summary:** 

<table>

<tr>

<td>

![Screenshot_20200109-042836](https://user-images.githubusercontent.com/19607555/72089367-eebd0300-3331-11ea-9f56-5c7de46d699d.jpg)
 Buggy UI 

</td>
<td>

![Screenshot_20200109-043109](https://user-images.githubusercontent.com/19607555/72089430-08f6e100-3332-11ea-8802-2b260713be0d.jpg)
Correct UI Part 1

</td>
<td>

![Screenshot_20200109-043104](https://user-images.githubusercontent.com/19607555/72089433-0a280e00-3332-11ea-912d-e2ebf4c9754b.jpg)
Correct UI Part 2

</td>
</tr>
</table>

**Steps to reproduce:** 

How can we reproduce the issue? 
Open Course Details Page
 
**Screen-shots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Would you like to work on the issue?**
No

**Comment by kulloveth** [comment]
fixing this
