### ISSUE TITLE
Refactor Course Details Page - all modules to MVVM 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#315]
**Describe the feature you'd like**

Refactor Course Details Page - all modules to MVVM. Offline support is not needed here. 
Each tab [student list/article list/upload list,..] can be done in a separate PR. 

**Would you like to work on the issue?**
No

**Comment by gconnect** [comment]
Okay. I will work on it

**Comment by kulloveth** [comment]
@gconnect any tab available on this issue?

**Comment by gconnect** [comment]
Yes there are tabs. If I understand what you meant

**Comment by ujjwalagrawal17** [comment]
I think she is asking if she can work on any of the sub-modules. I think we can divide this in 5 sub-issues for each tab and then pick up one by one.

**Comment by gconnect** [comment]
That will be great. Will create the sub issues

**Comment by kulloveth** [comment]
> I think she is asking if she can work on any of the sub-modules. I think we can divide this in 5 sub-issues for each tab and then pick up one by one.

yes that was what I meant

**Comment by ujjwalagrawal17** [comment]
@kulloveth you can take a module from last tabs maybe - recent activity or uploads. @gconnect can start from left side (Course Details Home, Student List, Article List,..)

**Comment by ujjwalagrawal17** [comment]
All sub-modules are done so closing this issue. Thanks @gconnect
