### ISSUE TITLE
Add Project Setup Steps in Readme 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#325]
**Describe the feature you'd like**

Add Project Setup Steps in Readme or https://github.com/WikiEducationFoundation/apps-android-wikiedudashboard/blob/master/docs/Android_App_Setup.md

Many newcomers are finding it difficult to set up the project without instructions. 

**Would you like to work on the issue?**
Probably No

**Comment by iamspathan** [comment]
Can I work on this issue?

**Comment by ujjwalagrawal17** [comment]
Sure.
