### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by IzzySoft** [WikiEducationFoundation/apps-android-wikiedudashboard#35]
Could you please clarify which statement is correct:

* License: MIT (as stated in the [LICENSE](https://github.com/WikiEducationFoundation/apps-android-wikiedudashboard/blob/master/LICENSE) file)
* License: Apache 2.0 (as stated at the bottom of the Readme)

Looks a bit contradicting :wink:

**Comment by ujjwalagrawal17** [comment]
Hi @izzysoft MIT licence will be the correct one. I will update the readme with that. 
Thanks

**Comment by IzzySoft** [comment]
Wow, that was fast – thank you! To make it easier on your users to install your app and keep it up-to-date, your app will be available via my repo [here](https://apt.izzysoft.de/fdroid/index/apk/org.wikiedufoundation.wikiedudashboard.release) (should show up within the next 10..15min). Updates will be grabbed automatically within 24h – though I'd recommend using [releases](https://github.com/WikiEducationFoundation/apps-android-wikiedudashboard/releases) and attaching the APK there instead of putting it inside the repo – so if your contributors clone the repo, a long history of APKs won't have bloated it (please let me know if you moved it, so I update my configuration to grab it from the right place).

PS: If you wish to have your app listed with the official F-Droid repo and need assistance, just let me know. While my repo works with the F-Droid client, the official one is more prominent and more trusted.

**Comment by ujjwalagrawal17** [comment]
Hi, @IzzySoft thanks for configuring automatic APK deployment. I planned to configure F-droid. Probably I will configure F-droid in next week. Also, Since the app is in development stage now we don't have a release APK version now. I will use releases after we will deploy the app on Google Play.

**Comment by ujjwalagrawal17** [comment]
Also, license is updated so closing this issue.

**Comment by IzzySoft** [comment]
@ujjwalagrawal17 thanks for your fast response! I'll continue picking the APK from inside the repo then (for now, so your testers have easier access). As soon as your app is listed in the official repo, I'll remove it again on my end (to avoid confusion with signature mismatches).

Feel free to ping me if you need help with the RFP for F-Droid then (disclosure: I'm one of the F-Droid maintainers). Pointers ahead: tags will be much appreciated (so we know what commit to build, and can detect when you made a new release) with the tag name corresponding to `versionName` (optionally prefixed with e.g. a `v`, like `v1.2.3` for `versionName: '1.2.3'`), plus Fastlane (or Triple-T) with screenshots, per-release changelogs and localized descriptions would be nice (you can use them to deploy to Play Store as well, so it's no "double work").

**Comment by ujjwalagrawal17** [comment]
Thanks, @IzzySoft . I will ping you if I will need help in the configuration.
