### ISSUE TITLE
Show list of users for a course in Course Detail Page

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#4]
**Describe the feature you'd like**

Allow users to see list of all users for a course in course detail page.

**Comment by ujjwalagrawal17** [comment]
**Example API URL:** https://dashboard.wikiedu.org/courses/Rice_University/Poverty,_Justice,_and_Human_Capabilities_(Fall_2018)/users.json

**Comment by xxrain-makerxx** [comment]
I want to work on this issue.
