### ISSUE TITLE
Show list of articles edited for course

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#5]
**Describe the feature you'd like**

Allow users to see a list of articles edited for course.

**Comment by ujjwalagrawal17** [comment]
**Example API URL:**  https://dashboard.wikiedu.org/courses/Rice_University/Poverty,_Justice,_and_Human_Capabilities_(Fall_2018)/articles.json

**Comment by Aman563** [comment]
Sir I want to work on this issue
