### ISSUE TITLE
Migrate from LeakCanary 1 to LeakCanary 2.0. 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#51]
**Describe the feature you'd like**

**Advantages:** https://www.youtube.com/watch?v=LEX8dn4BLUw

**Comment by ShridharGoel** [comment]
The project is already using version `2.0-alpha-2`.

**Comment by ujjwalagrawal17** [comment]
Yup @ShridharGoel, we are closing this issue.
