### ISSUE TITLE
[BUG] Can't log in

### ISSUE THREAD

**Issue by Samwalton9** [WikiEducationFoundation/apps-android-wikiedudashboard#52]
**Summary:** 

When logging in on my phone, I reach a blank screen and can't progress.

**Steps to reproduce:** 

I signed in via Wikipedia, logged in to my account, clicked Allow, and then ended up at the screenshot below. If I close the app and re-open it, I'm prompted to log in again.

**Device and Android version:** 

Huawei P10, EMUI 9.0.1 (Android 9)
 
**Screen-shots:** 

![Wiki Ed app](https://user-images.githubusercontent.com/12038840/64343754-06335a80-cfe5-11e9-9643-f202809a483b.jpg)

**Comment by ujjwalagrawal17** [comment]
Hi Sam, can you share the place from which you installed the app? Did you
installed it from Google Play store?

**Comment by Samwalton9** [comment]
Yes, the Google Play Store.

**Comment by ujjwalagrawal17** [comment]
seems to be a device specific issue. I tried it in 2 different devices, seems to work fine. Will try to look into it soon.

**Comment by melissasny1** [comment]
Hi Ujjwal, I would like to work on this issue, Melissa

**Comment by ujjwalagrawal17** [comment]
Hi @melissasny1 , are you able to reproduce the issue? If yes, feel free to start working on the issue.

**Comment by melissasny1** [comment]
Yes, I am able to reproduce the issue and will work on it.

**Comment by ujjwalagrawal17** [comment]
Okay. I am assigning this issue to you then.

**Comment by victorvicari** [comment]
Hi.. I've had the same experience. I'm currently using an Asus smartphone.
