### ISSUE TITLE
[BUG] Scrolling issue in Media Details Page. 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#57]
**Summary:**

Profile Page scrolling is not smooth.

**Steps to reproduce:**

- Login to the app.
- Open any courses and go to uploads section.
- Try scrolling in the category section of the page. 

**Device and Android version:**

**Model No:** Moto G5S+
**Android version:** 8.1.1

**Would you like to work on the issue?**
No

**Comment by gconnect** [comment]
I would like to work on this issue

**Comment by ujjwalagrawal17** [comment]
Sure, feel free to start working on it. send a PR once it's solved.

**Comment by gconnect** [comment]
Please I sent you a mail to your personal mail ujjwal.iitism@gmail.com, I hope its correct?. I just got approval for the inital round of the Outreachy 2019. And I would like to contribute to the Wikimedia Education Dashoboard Project. I would need your mentorship guide. I followed you on twitter wanted to reach out to you but your private messaging is not accessible.
Here is my email: agatevureglory@gmail.com
Twitter : @agatevureglory
I would like to have the link to Wikimedia slack channel so I can join. Thanks.

**Comment by ujjwalagrawal17** [comment]
I have asked Sage to send you an invite for Slack. Also, I am assigning this issue to you.

**Comment by gconnect** [comment]
Okay thanks.

**Comment by gconnect** [comment]
I just made a pull request now.

**Comment by ujjwalagrawal17** [comment]
Thanks @gconnect , I will review the PR soon.
