### ISSUE TITLE
[Feature] Add Download option in media details page.  

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#61]
**Describe the feature you'd like**

Download option in current media page is not working, it should ideally download the image and send a notification to the user once it is downloaded. 

**Would you like to work on the issue?**

No

**Comment by kiranofans** [comment]
I'm an Outreachy applicant, I would like to try to solve this issue.

**Comment by ujjwalagrawal17** [comment]
Hi @kiranofans, okay I am assigning it to you.

**Comment by kiranofans** [comment]
@ujjwalagrawal17 Hi thanks for the assignment. Also, I'm not sure how to create a sub-issue for #62, not very familiar with the issue tracker

**Comment by ujjwalagrawal17** [comment]
@kiranofans, have you made any progress on this issue @shu also wants to work on this issue.

**Comment by ujjwalagrawal17** [comment]
@kiranofans have you made any progress in the PR. Are you facing any issues in the implementation? We also need to ask for storage permission when user clicks on the button and we don't have the permission.

**Comment by kiranofans** [comment]
@ujjwalagrawal17 I'm still looking into it. Not sure which api to use to download the image

**Comment by ujjwalagrawal17** [comment]
We have the image url so you can simply download the image from the Url. You don't need to learn about mediawiki APIs for that.

**Comment by kiranofans** [comment]
@ujjwalagrawal17 
I also got the problem with testing this feature. login to Outreach Program and Event still crashes, and log in to WkiEducation Dashboard I only got the purple page.

**Comment by ujjwalagrawal17** [comment]
I guess it should be fixed as #52 is now solved for WikiEducation Dashboard Login . @kiranofans can you pull the updated code and check if you are still facing the issue.

**Comment by kiranofans** [comment]
@ujjwalagrawal17 the crash still occurs on my phone (Android 6.0), but it's ok with the emulator (Android 9.0)

**Comment by kiranofans** [comment]
I have some technical problem with implementing this feature.
How can I download an image using URL (thumbUrl)? 
I'm trying with this line: 
`            val inputStream:InputStream = BufferedInputStream(url.openStream())
`
and I got NetworkOnMainThreadException
