### ISSUE TITLE
Use constraint Layout in all layout files instead of Relative, Linear Layouts. 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#62]
**Describe the feature you'd like**

Use constraint Layout in all layout files instead of Relative, Linear Layouts to improve app performance by reducing the number of nested layouts. 

This is the parent issue. There will be multiple sub-issues for each activity/fragment.

**Would you like to work on the issue?**

No.

**Comment by kulloveth** [comment]
@ujjwalagrawal17  can I start working on this?

**Comment by ujjwalagrawal17** [comment]
@kulloveth can you create a sub-issue in which page you want to work. We will work on the pages one by one instead of all in 1 PR.

**Comment by Anniekobia** [comment]
I am an outreachy applicant and would love to work on this issue. How do i create a sub issue? @ujjwalagrawal17

**Comment by ujjwalagrawal17** [comment]
It is done in all of the layouts so closing this issue.
