### ISSUE TITLE
Update Screenshots in Readme.md

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#63]
**Describe the feature you'd like**

The screenshots in the app are not updated from last 6 months and are outdated. We need to update screenshots in Readme.md.

**Would you like to work on the issue?**
No

**Comment by meemah** [comment]
I am an Outreachy applicant, please can i work on this?

**Comment by ujjwalagrawal17** [comment]
@meemah sure, you can start working on it.

**Comment by meemah** [comment]
I dont know if its just me, but in trying to take screenshots, I am having issues with the app, attached here is the image 
![Screenshot_1570504694](https://user-images.githubusercontent.com/26439738/66419393-f780fe80-e9fb-11e9-83e9-d8fd67ad1ceb.png)

**Comment by kulloveth** [comment]
@meemah  are you still working on this? @ujjwalagrawal17  what do you think about me making those updates so many things have changed in the UI

**Comment by meemah** [comment]
Hello @kulloveth yes I am still working on it,I should be done with it by tomorrow

**Comment by kulloveth** [comment]
Alright @meemah
