### ISSUE TITLE
[Sub-issue] Use Contraint Layout in activity_media_detail.xml

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#65]
Describe the feature you'd like

This is a sub-issue of #62

Would you like to work on the issue?

No

**Comment by MarinaTaran** [comment]
Ok. I will take this one! Can you add me to Slack?! I will sent you mail now

**Comment by ujjwalagrawal17** [comment]
Yes. You can work on this issue.

**Comment by MarinaTaran** [comment]
Thanks!

**Comment by MarinaTaran** [comment]
should I get some permission from you?

**Comment by ujjwalagrawal17** [comment]
No. You can start working on it. Once it is fixed, send a pull request for the same.

**Comment by MarinaTaran** [comment]
Hello. I have problem with pushing. I created new branch for my changes and tried to push but I got error - I don't have permission, permission  denied, the requested URL returned error: 403

**Comment by ujjwalagrawal17** [comment]
You have to push it on your forked repo and then send a Pull Request. You don't have permission to push in the main repo now.

**Comment by ujjwalagrawal17** [comment]
Step 1: fork the repo
Step 2: Clone the repo
Step 3: Make a new branch from master to work on your changes (Ex. - issue65)
Step 4: Work on issue65 and push it in your forked repo. 
Step 5: Send a PR from issue65 branch of forked repo to master of main repo.

**Comment by MarinaTaran** [comment]
I sent PR. Thanks!
