### ISSUE TITLE
[Sub-issue] Use Contraint Layout in activity_settings.xml

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#66]
Describe the feature you'd like

This is a sub-issue of #62

Would you like to work on the issue?

No

**Comment by ShridharGoel** [comment]
I'm working on this.

**Comment by kulloveth** [comment]
I want to work on this

**Comment by kiranofans** [comment]
Can I work on this issue?

**Comment by ujjwalagrawal17** [comment]
Since @kulloveth first told that she wants to work on this so I am assigning it to her.

**Comment by ujjwalagrawal17** [comment]
@kiranofans you can work on other open issues or create new issues. #62 will be splitted into 15-20 issues. It will be nice if you can create sub-issues for that, send PRs for some of the sub-issues.

**Comment by ujjwalagrawal17** [comment]
Closed by # 71. @kulloveth Thanks for your work.
