### ISSUE TITLE
Show all uploads for a course

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#7]
**Describe the feature you'd like**

Allow users to see all uploads for a course.

**Comment by ujjwalagrawal17** [comment]
Example API URL: https://dashboard.wikiedu.org/courses/Rice_University/Poverty,_Justice,_and_Human_Capabilities_(Fall_2018)/uploads.json

**Comment by sreyans01** [comment]
I will opt for this one.
