### ISSUE TITLE
[Sub-issue] Use Constraint Layout in fragment_media_details.xml 

### ISSUE THREAD

**Issue by kiranofans** [WikiEducationFoundation/apps-android-wikiedudashboard#76]
**To apply ConstraintLayout to fragment_media_details.xml**

This is a sub-issue of  #62

**Would you like to work on the issue?**

Yes

This sub-issue seems been duplicated, I'm not sure what to do now.

**Comment by gconnect** [comment]
I have converted the layout to Constraint along side fixing the scrolling issue on the fragment media details.xml. Please check my pull request for review. Thanks.

**Comment by ujjwalagrawal17** [comment]
@kiranofans since @gconnect has already worked on it can you work on some other issue. You can create a similar issue for other page. 

We will make sure issue created by you is not assigned to some other person if you are interested in working on it from next time.

**Comment by kiranofans** [comment]
@ujjwalagrawal17 Sure, I just found out this issue has been duplicated, my mistake. And I'm not sure what can I do with this one
