### ISSUE TITLE
Add Documentation for undocumented methods/classes

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#80]
**Describe the feature you'd like**

Add Documentation for undocumented methods/classes. Further discussion about how to document kotlin code in Android following best practices will be appreciated. 

**Would you like to work on the issue?**

No.

**Comment by ujjwalagrawal17** [comment]
Also we can divide this issue in smaller tasks to easily get started.

**Comment by kiranofans** [comment]
I will try to document all the methods/classes

**Comment by ujjwalagrawal17** [comment]
Can you send different PRs for different classes/3-4 classes? Reviewing 20-30 classes in 1 PR will be very difficult for me.

**Comment by kiranofans** [comment]
@ujjwalagrawal17 sure. So which type of class or methods should be documented? Like customized ones?

**Comment by ujjwalagrawal17** [comment]
All the classes, methods written by us should have documentation.

**Comment by kiranofans** [comment]
I think this issue can be closed?

**Comment by ujjwalagrawal17** [comment]
Thanks @kiranofans
