### ISSUE TITLE
Write Documentation for newcomers to easily get started with the project

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/apps-android-wikiedudashboard#81]
**Describe the feature you'd like**

Write documentation for newcomers to: 
1. Setup Android App.
2. Creating Account, Login to the dashboard.
3. Joining a course using dashboard website. 

Any other thing that new comers need.

**Comment by meemah** [comment]
I am Outreachy applicant, please can this task be assigned to me

**Comment by ujjwalagrawal17** [comment]
Will assign it once you send a PR for the previous assigned issues. 2 issues are already assigned to you.

**Comment by gconnect** [comment]
You can assign it to me

**Comment by ujjwalagrawal17** [comment]
@gconnect, sure you can work on it if your previous work is completed.

**Comment by gconnect** [comment]
My previous works are completed waiting for you to review and close the issue

**Comment by ujjwalagrawal17** [comment]
Please work on a seperate branch from created from master.

**Comment by gconnect** [comment]
You mean I should create a branch directly on the master?

**Comment by ujjwalagrawal17** [comment]
Yes.

**Comment by arps18** [comment]
Hey @ujjwalagrawal17  I want to contribute how can I do so?

**Comment by ujjwalagrawal17** [comment]
Hi, @arps18 you can start off with #56  if you want.

**Comment by vivekvj18** [comment]
Hey Hello,
@ujjwalagrawal17 Can I Get This Task...?

**Comment by gconnect** [comment]
@vivekvj18 you can work on it

**Comment by vivekvj18** [comment]
@ujjwalagrawal17 
@gconnect 
Do I Need To Add Change The Docs File In The Project...?

**Comment by vivekvj18** [comment]
@ujjwalagrawal17 
@gconnect 
I Have Created This Pull Request By Making A New File Creating_Account .
Please Check This And Approve It So That I Can Make New File For Joining a course using dashboard website.

**Comment by vivekvj18** [comment]
@ujjwalagrawal17 
@gconnect 
I Have Created This Pull Request By Making A New File Creating_Account .
Please Check This And Approve It So That I Can Make New File For Joining a course using dashboard website.
