### ISSUE TITLE
User experience issue. Unable to access the outreachy dashboard without swiping

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#82]
**Improve the user experience of the Outreachy Programs Dashboard login**

**Requirements**
- After the splash screen the welcome activity should launch the fragment where the user can choose between Wiki Education Dashboard and Outreachy Program Dashboard
- Base on user selection. The user should be logged in into the appropriate Dashboard

**Would you like to work on the issue?**
I would like to work on the issue

**Comment by ujjwalagrawal17** [comment]
The way I was thinking of the implementation for this was. 
Splash -> Welcome Activity (consisting of 4 pages). 
Page1, Page 2 will have some images, text telling more about the app (onboarding pages)
Page 3 will be for WikiEdu Dashboard. 
Page 4 will be for P&E Dashboard. 
Maybe we can show dots in the bottom of the screen. That way user will know he/she can swipe left/right.

**Comment by ujjwalagrawal17** [comment]
@gconnect what do you think about implementing it this way ?

> The way I was thinking of the implementation for this was.
> Splash -> Welcome Activity (consisting of 4 pages).
> Page1, Page 2 will have some images, text telling more about the app (onboarding pages)
> Page 3 will be for login & signup for WikiEdu Dashboard.
> Page 4 will be for login & signup for P&E Dashboard.
> Maybe we can show dots in the bottom of the screen. That way user will know he/she can swipe left/right.

**Comment by gconnect** [comment]
OKay, it's fine. I would like to work on it.

**Comment by gconnect** [comment]
Am working on it. Here is the mockup of the on boarding I came up with. let
me know what you think before I go ahead and implement it.
https://www.figma.com/file/vkH3YZOxVqPuBmCVhSVX4z/Wikimedia-designs?node-id=1%3A139

https://www.figma.com/proto/vkH3YZOxVqPuBmCVhSVX4z/Wikimedia-designs?node-id=0%3A1&scaling=min-zoom

**Comment by ujjwalagrawal17** [comment]
@gconnect  Mockups are looking great! 

1. The background of the last 2 slides looks a little simple to me. Will be great if the last 2 pages can be improved. 
2. What will happen in a click of get-started in last page? If nothing, let's remove that button. 
3. I think the colour code used in the design is not the accent colour of the app. It's #575d99 in case you need it.

**Comment by ujjwalagrawal17** [comment]
@ragesoss would like your review on the new onboarding page of the app.

**Comment by gconnect** [comment]
Thanks for your response. Your comments are noted!

**Comment by gconnect** [comment]
The login with wikipedia and signup with wikipedia, do they take the user
to exactly the same page/route when done from either of Outreach Program
event dashboard and Wiki Education Dashboard. I want to know so that I
might not have to repeat those login and signup button on both Wiki Edu and
Outreach Dashboard.

**Comment by ujjwalagrawal17** [comment]
The user group of both the dashboards are very different and there will probably be no user except the developers, WikiEd team who have accounts on both the servers. I think we should have separate screens for both.

**Comment by gconnect** [comment]
Will keep them separate as it is and redesign it.

**Comment by gconnect** [comment]
Here is the new design with the color code you provided. You can check them
out with the previous links I sent.

**Comment by ujjwalagrawal17** [comment]
Looks good. You can start the implementation for the same.

**Comment by gconnect** [comment]
Okay thanks

**Comment by gconnect** [comment]
Can you close this for the acceptance of the design? While I implement the onboarding and send PR here https://github.com/WikiEducationFoundation/apps-android-wikiedudashboard/issues/23

**Comment by ujjwalagrawal17** [comment]
Sure.
