### ISSUE TITLE
Change the Welcome Activity to use Navigation Components

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#83]
**Eliminate the use of fragment transaction to Android Navigation Component**

**Requirements**
-Use the Welcome Activity as the host Activity 
- Create a nav-grapgh
- The Wiki Education Dashboard Fragment and Outreach Program Dashboard will be hosted by the welcome activity and using the Android Navigation Component Graph

**Would you like to work on the issue?**

I would like to work on it.

**Comment by ujjwalagrawal17** [comment]
Assigned to you.

**Comment by gconnect** [comment]
Completed
