### ISSUE TITLE
The Hardcoded strings should be changed to use @String resources

### ISSUE THREAD

**Issue by kulloveth** [WikiEducationFoundation/apps-android-wikiedudashboard#84]

**Comment by kulloveth** [comment]
1 Creating string resources for the hardcoded text
2 Referencing them in their respective Layout files

**Comment by kulloveth** [comment]
Am thinking this could be divided int sub issues for each layout what do you think? @ujjwalagrawal17

**Comment by ujjwalagrawal17** [comment]
Yes, it should be. That will make it easy to implement.

**Comment by mayokunthefirst** [comment]
Hello, i'll love to get on this...

**Comment by kulloveth** [comment]
This is is in progress already

**Comment by mayokunthefirst** [comment]
> This is in progress already

Yeah, I picked from the comments above that you suggested it be divided into sub issues.  Can I still jump on this ?

**Comment by Anniekobia** [comment]
Hello, I am an outreachy applicant and would love to contribute to this if its still open? @ujjwalagrawal17 
@ragesoss

**Comment by 7phalange7** [comment]
Looks like several people have already worked on this. It's still open so I wanted to inquire if I can still work on it?

**Comment by ujjwalagrawal17** [comment]
Yes, it is still pending in some of the pages. If you find and fix them you
can raise a PR for the same.

**Comment by 7phalange7** [comment]
> Yes, it is still pending in some of the pages. If you find and fix them you can raise a PR for the same.

I checked and all the files in res layout have already been changed to string resources

**Comment by ujjwalagrawal17** [comment]
Okay. Closing this issue then. Thanks everyone for your contributions.

**Comment by gconnect** [comment]
Inside the Fragments and Activities, I think there are still some hardcoded strings there

**Comment by Bhavnaharitsa** [comment]
@gconnect Can I work on this?

**Comment by gconnect** [comment]
You can work on it
