### ISSUE TITLE
[Sub-issue] Use ConstraintLayout in  fragment_outreach_programs_dashboard.xml

### ISSUE THREAD

**Issue by kulloveth** [WikiEducationFoundation/apps-android-wikiedudashboard#85]
Removing the Relative Layout and LinearLayout and use constraintLayout instead

Would you like to work on this 

Yes

**Comment by kulloveth** [comment]
@ujjwalagrawal17  I want to work on this

**Comment by ujjwalagrawal17** [comment]
You already have 2 assigned issues for which you haven't sent PR. I will assign it to you once you complete previous issues.

**Comment by kulloveth** [comment]
@ujjwalagrawal17  I asked a question regarding #84 waiting for response

**Comment by kulloveth** [comment]
for #64 since I am having an unmerged pull request am not able to create another one seems like its pilling up, how do I fix that @ujjwalagrawal17

**Comment by ujjwalagrawal17** [comment]
No, you can create multiple PRs by working on different branches.

**Comment by kulloveth** [comment]
Ok, will do that now

**Comment by ujjwalagrawal17** [comment]
@kulloveth do we have a PR for this ?

**Comment by kulloveth** [comment]
that has been fixed already, I think you should close it

**Comment by ujjwalagrawal17** [comment]
Thanks.
