### ISSUE TITLE
[sub-issue] Use constraint layout in Wiki Education Dashboard Fragment

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#97]
**Change the Layout to Constraint Layout**

**Would you like to work on the issue?**

Yes

**Comment by ujjwalagrawal17** [comment]
This can be implemented along with #23

**Comment by gconnect** [comment]
Yes sure! Am on it.

**Comment by gconnect** [comment]
I have completed it
