### ISSUE TITLE
Change the SplashScreen Activity to Fragment and use constraint layout

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#99]
**Change to Fragment and Constraint Layout**

* The splash screen activity will be change to fragment and hosted by a WelcomeHostActivity along side other welcome fragments
* The splash screen will now use constraint layout

**Would you like to work on the issue?**
Yes

**Comment by ujjwalagrawal17** [comment]
I think it's a good idea to keep splash screen seperated from welcomeHostActivity. We have written our logic for redirecting to welcomeActivity/HomeActivity inside Splash Screen. If needed we can make Splash Screen fragment and host it in current Splash Activity. But I don't think it's needed as of now. 

If you have some specific reason why we want to host it in WelcomeHostActivity, please let us know.

**Comment by gconnect** [comment]
I will just make do with the existing splashscreen Activity

**Comment by gconnect** [comment]
The reason I said it should be a fragment its because I just want to reduce
our usage of Activities and leverage on Navigation component with fragment.
We will still maintain the existing logic from the splash screen Activity.
However if you feel its not necessary we can always do it later.

**Comment by ujjwalagrawal17** [comment]
Let's not do it for now.

**Comment by gconnect** [comment]
Okay.

**Comment by gconnect** [comment]
The Splashscreen still remain an Activity but I have changed it to Constraint layout. I had a conflict while making pull request. I need access to resolve it.Thanks

**Comment by ujjwalagrawal17** [comment]
Just checked, splash is already changed to constraint layout in #72 . So closing this issue.
